---
name: Publish
run-name: Publish ${{ inputs.tag }} to PyPI

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
      tag:
        type: string
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
     id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use "3.12"
          poetry install

      - name: Bump version number
        run: poetry version ${{ inputs.tag }}

      - name: Build package
        run: poetry build

      - name: Publish to test pypi
        if: inputs.stage == 'test'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: 'https://test.pypi.org/legacy/'

      - name: Publish to prod pypi
        if: inputs.stage == 'prod'
        uses: pypa/gh-action-pypi-publish@release/v1

  determine-success:
    needs:
      - build-and-publish
    runs-on: ubuntu-latest
    if: always()
    outputs:
      success: ${{ steps.success.outputs.success }}
    steps:
      - id: success
        run: |
          if [[ "${{ needs.build-and-publish.result }}" == "success" ]]; then
              echo "success=true" >> $GITHUB_OUTPUT
          else
              echo "success=false" >> $GITHUB_OUTPUT
          fi

  notify-slack:
    if: inputs.stage == 'prod' && always()
    uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/slack-notify.yml@main
    needs:
      - build-and-publish
      - determine-success
    with:
      WORKFLOW_PASSED: ${{ needs.determine-success.outputs.success == 'true' }}
      SUCCESS_PAYLOAD: "{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\":airplane: ${{ github.repository }} - Successfully deployed ${{ inputs.tag }} :large_green_circle:\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Package published to PyPI successfully\"}}]}"
      FAILURE_PAYLOAD: "{\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\":x: ${{ github.repository }} - Failed to deploy ${{ inputs.tag }} :x:\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Failed to publish package to PyPI\"}}]}"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
