name: Run tests
on:
  push:

jobs:
  test:
    runs-on: "macos-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use "3.12"
          poetry install

      - name: Run Checks
        run: |
          bash scripts/test.sh --ci

      - name: Bump version number
        run: poetry version 0.0.0

      - name: Build package
        run: poetry build

      - name: Publish to test pypi
        if: github.ref_name == github.event.repository.default_branch
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: 'https://test.pypi.org/legacy/'
