name: Run tests
on:
  push:
  workflow_call:

jobs:
  test-code:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use python
          poetry install

      - name: Run Checks
        run: |
          bash scripts/test.sh --ci

  test-publish:
    needs:
      - test-code
    uses: i-dot-ai/cruft-iai/.github/workflows/publish.yml@EN-623/package_hosting
    with:
      stage: test
      tag: "0.0.0"
